name: image_collage_exemple
description: flutter widget component that renders the images collaged like facebook deos
version: 1.0.3+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  like_button: ^2.0.4

  image_collage:
    # path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true